-- mayukai — standalone Neovim port of ../helix/themes/mayukai.toml.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end
vim.o.termguicolors = true
vim.o.background = "dark"
vim.g.colors_name = "mayukai"

local p = {
  bg = "#101521",
  fg = "#dadbc0",
  text_muted = "#707a8c",
  surface = "#232834",
  panel_bg = "#1f2430",
  active_line = "#191e2a",
  selection = "#3d424d",
  element_active = "#4e545f",
  border = "#373e4c",
  cursor = "#ffcc66",
  accent = "#ffcc66",
  linenr = "#586070",
  linenr_active = "#9aa3b2",
  invisible = "#4a505c",
  indent_guide = "#4a505c",

  comment = "#5c6773",
  string = "#bae67e",
  string_special = "#95e6cb",
  number = "#9dd2bb",
  constant = "#f29668",
  constant_builtin = "#d4bfff",
  variable_builtin = "#f28779",
  variable_member = "#f28779",
  type = "#ff8f40",
  variant = "#ff8f40",
  keyword = "#ffa759",
  keyword_control = "#f07178",
  operator = "#ff6188",
  func = "#ffcc66",
  function_builtin = "#ffd580",
  tag = "#fc4085",
  icon = "#b3b1ad",
  label = "#bae67e",
  punctuation = "#cbccc6",
  title = "#bae67e",
  emphasis = "#f28779",
  link_text = "#95e6cb",
  link_uri = "#95e6cb",
  text_literal = "#f29e74",

  diff_plus = "#a6cc70",
  diff_minus = "#f27983",
  diff_delta = "#77a8d9",
  warning = "#ffcc66",
  error_red = "#ff3333",
  info_color = "#95e6cb",
  hint_color = "#5c6773",
  search_match = "#f6466f",
}

local hl = function(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

local groups = {
  -- Editor UI
  Normal = { fg = p.fg, bg = p.bg },
  NormalNC = { fg = p.fg, bg = p.bg },
  NormalFloat = { fg = p.fg, bg = p.surface },
  FloatBorder = { fg = p.border, bg = p.surface },
  FloatTitle = { fg = p.accent, bg = p.surface, bold = true },
  Cursor = { fg = p.bg, bg = p.cursor },
  lCursor = { fg = p.bg, bg = p.cursor },
  TermCursor = { fg = p.bg, bg = p.cursor },
  CursorLine = { bg = p.active_line },
  CursorColumn = { bg = p.active_line },
  ColorColumn = { bg = p.active_line },
  LineNr = { fg = p.linenr },
  CursorLineNr = { fg = p.linenr_active },
  SignColumn = { fg = p.linenr, bg = p.bg },
  FoldColumn = { fg = p.linenr, bg = p.bg },
  Folded = { fg = p.text_muted, bg = p.surface },
  Visual = { bg = p.selection },
  VisualNOS = { bg = p.selection },
  MatchParen = { fg = p.bg, bg = p.search_match, bold = true },
  Search = { fg = p.bg, bg = p.warning },
  IncSearch = { fg = p.bg, bg = p.search_match },
  CurSearch = { fg = p.bg, bg = p.search_match },
  Substitute = { fg = p.bg, bg = p.error_red },
  WinSeparator = { fg = p.border },
  VertSplit = { fg = p.border },
  EndOfBuffer = { fg = p.bg },
  NonText = { fg = p.invisible },
  Whitespace = { fg = p.invisible },
  SpecialKey = { fg = p.text_muted },
  Conceal = { fg = p.text_muted },
  Directory = { fg = p.accent },
  Title = { fg = p.title, bold = true },

  -- Messages / cmdline
  ModeMsg = { fg = p.fg },
  MoreMsg = { fg = p.string },
  Question = { fg = p.string },
  ErrorMsg = { fg = p.error_red, bold = true },
  WarningMsg = { fg = p.warning },
  MsgArea = { fg = p.fg },

  -- Statusline / tabline
  StatusLine = { fg = p.fg, bg = p.surface },
  StatusLineNC = { fg = p.text_muted, bg = p.panel_bg },
  TabLine = { fg = p.text_muted, bg = p.panel_bg },
  TabLineSel = { fg = p.fg, bg = p.surface, bold = true },
  TabLineFill = { bg = p.panel_bg },
  WinBar = { fg = p.fg, bg = p.bg },
  WinBarNC = { fg = p.text_muted, bg = p.bg },

  -- Popup menu
  Pmenu = { fg = p.fg, bg = p.surface },
  PmenuSel = { fg = p.fg, bg = p.element_active },
  PmenuSbar = { fg = p.text_muted, bg = p.surface },
  PmenuThumb = { bg = p.text_muted },
  WildMenu = { fg = p.fg, bg = p.element_active },
  QuickFixLine = { bg = p.active_line },

  -- Base syntax
  Comment = { fg = p.comment, italic = true },
  Constant = { fg = p.constant },
  String = { fg = p.string },
  Character = { fg = p.string },
  Number = { fg = p.number },
  Boolean = { fg = p.constant_builtin },
  Float = { fg = p.number },
  Identifier = { fg = p.fg },
  Function = { fg = p.func },
  Statement = { fg = p.keyword },
  Conditional = { fg = p.keyword_control },
  Repeat = { fg = p.keyword_control },
  Label = { fg = p.label },
  Operator = { fg = p.operator },
  Keyword = { fg = p.keyword },
  Exception = { fg = p.keyword_control },
  PreProc = { fg = p.keyword },
  Include = { fg = p.keyword },
  Define = { fg = p.keyword },
  Macro = { fg = p.function_builtin },
  PreCondit = { fg = p.keyword },
  Type = { fg = p.type },
  StorageClass = { fg = p.keyword, italic = true },
  Structure = { fg = p.type },
  Typedef = { fg = p.type },
  Special = { fg = p.keyword },
  SpecialChar = { fg = p.string_special },
  Tag = { fg = p.tag },
  Delimiter = { fg = p.punctuation },
  SpecialComment = { fg = p.comment, italic = true },
  Debug = { fg = p.keyword },
  Underlined = { fg = p.link_uri, underline = true },
  Ignore = { fg = p.text_muted },
  Error = { fg = p.error_red },
  Todo = { fg = p.accent, bold = true },

  -- Treesitter captures
  ["@comment"] = { fg = p.comment, italic = true },
  ["@comment.documentation"] = { fg = p.comment, italic = true },
  ["@variable"] = { fg = p.fg },
  ["@variable.builtin"] = { fg = p.variable_builtin, italic = true },
  ["@variable.parameter"] = { fg = p.fg },
  ["@variable.member"] = { fg = p.fg },
  ["@property"] = { fg = p.fg },
  ["@field"] = { fg = p.fg },

  ["@constant"] = { fg = p.constant },
  ["@constant.builtin"] = { fg = p.constant_builtin },
  ["@constant.macro"] = { fg = p.constant },
  ["@number"] = { fg = p.number },
  ["@number.float"] = { fg = p.number },
  ["@boolean"] = { fg = p.constant_builtin },

  ["@string"] = { fg = p.string },
  ["@string.regexp"] = { fg = p.string_special },
  ["@string.escape"] = { fg = p.string_special },
  ["@string.special"] = { fg = p.string_special },
  ["@string.special.symbol"] = { fg = p.string },
  ["@string.special.path"] = { fg = p.string_special },
  ["@string.special.url"] = { fg = p.link_uri },
  ["@character"] = { fg = p.string },
  ["@character.special"] = { fg = p.string_special },

  ["@function"] = { fg = p.func },
  ["@function.call"] = { fg = p.func },
  ["@function.builtin"] = { fg = p.function_builtin },
  ["@function.macro"] = { fg = p.function_builtin },
  ["@function.method"] = { fg = p.func },
  ["@function.method.call"] = { fg = p.func },
  ["@constructor"] = { fg = p.type },
  ["@attribute"] = { fg = p.func, italic = true },

  ["@type"] = { fg = p.type },
  ["@type.builtin"] = { fg = p.type },
  ["@type.definition"] = { fg = p.type },
  ["@type.qualifier"] = { fg = p.keyword },

  ["@keyword"] = { fg = p.keyword },
  ["@keyword.function"] = { fg = p.keyword_control, italic = true },
  ["@keyword.operator"] = { fg = p.operator },
  ["@keyword.import"] = { fg = p.keyword },
  ["@keyword.storage"] = { fg = p.keyword, italic = true },
  ["@keyword.repeat"] = { fg = p.keyword_control },
  ["@keyword.return"] = { fg = p.keyword_control },
  ["@keyword.conditional"] = { fg = p.keyword_control },
  ["@keyword.exception"] = { fg = p.keyword_control },
  ["@keyword.directive"] = { fg = p.keyword },
  ["@keyword.coroutine"] = { fg = p.keyword_control },

  ["@operator"] = { fg = p.operator },
  ["@punctuation.delimiter"] = { fg = p.punctuation },
  ["@punctuation.bracket"] = { fg = p.fg },
  ["@punctuation.special"] = { fg = p.keyword },

  ["@module"] = { fg = p.keyword },
  ["@namespace"] = { fg = p.keyword },
  ["@label"] = { fg = p.label },

  ["@tag"] = { fg = p.tag },
  ["@tag.attribute"] = { fg = p.func, italic = true },
  ["@tag.delimiter"] = { fg = p.icon },

  -- Markup
  ["@markup.heading"] = { fg = p.title, bold = true },
  ["@markup.strong"] = { fg = p.emphasis, bold = true },
  ["@markup.italic"] = { fg = p.emphasis, italic = true },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.raw"] = { fg = p.text_literal },
  ["@markup.raw.block"] = { fg = p.text_literal },
  ["@markup.link"] = { fg = p.link_text, italic = true },
  ["@markup.link.label"] = { fg = p.link_text },
  ["@markup.link.url"] = { fg = p.link_uri, underline = true },
  ["@markup.list"] = { fg = p.function_builtin },
  ["@markup.quote"] = { fg = p.punctuation, italic = true },
  ["@markup.math"] = { fg = p.text_literal },

  ["@diff.plus"] = { fg = p.diff_plus },
  ["@diff.minus"] = { fg = p.diff_minus },
  ["@diff.delta"] = { fg = p.diff_delta },

  -- LSP semantic tokens
  ["@lsp.type.namespace"] = { link = "@module" },
  ["@lsp.type.type"] = { link = "@type" },
  ["@lsp.type.class"] = { link = "@type" },
  ["@lsp.type.enum"] = { link = "@type" },
  ["@lsp.type.interface"] = { link = "@type" },
  ["@lsp.type.struct"] = { link = "@type" },
  ["@lsp.type.typeParameter"] = { link = "@type" },
  ["@lsp.type.parameter"] = { link = "@variable.parameter" },
  ["@lsp.type.variable"] = { link = "@variable" },
  ["@lsp.type.property"] = { link = "@property" },
  ["@lsp.type.enumMember"] = { link = "@constant" },
  ["@lsp.type.function"] = { link = "@function" },
  ["@lsp.type.method"] = { link = "@function.method" },
  ["@lsp.type.macro"] = { link = "@function.macro" },
  ["@lsp.type.keyword"] = { link = "@keyword" },
  ["@lsp.type.comment"] = { link = "@comment" },
  ["@lsp.type.string"] = { link = "@string" },
  ["@lsp.type.number"] = { link = "@number" },
  ["@lsp.type.operator"] = { link = "@operator" },
  ["@lsp.type.decorator"] = { link = "@attribute" },

  -- Diagnostics
  DiagnosticError = { fg = p.error_red },
  DiagnosticWarn = { fg = p.warning },
  DiagnosticInfo = { fg = p.info_color },
  DiagnosticHint = { fg = p.hint_color },
  DiagnosticOk = { fg = p.diff_plus },
  DiagnosticVirtualTextError = { fg = p.error_red },
  DiagnosticVirtualTextWarn = { fg = p.warning },
  DiagnosticVirtualTextInfo = { fg = p.info_color },
  DiagnosticVirtualTextHint = { fg = p.hint_color },
  DiagnosticUnderlineError = { undercurl = true, sp = p.error_red },
  DiagnosticUnderlineWarn = { undercurl = true, sp = p.warning },
  DiagnosticUnderlineInfo = { undercurl = true, sp = p.info_color },
  DiagnosticUnderlineHint = { undercurl = true, sp = p.hint_color },
  DiagnosticUnnecessary = { fg = p.text_muted },
  DiagnosticDeprecated = { strikethrough = true },

  LspInlayHint = { fg = p.hint_color, bg = p.bg, italic = true },
  LspReferenceText = { bg = p.active_line },
  LspReferenceRead = { bg = p.active_line },
  LspReferenceWrite = { bg = p.active_line },

  -- vimdiff
  DiffAdd = { fg = p.diff_plus },
  DiffChange = { fg = p.diff_delta },
  DiffDelete = { fg = p.diff_minus },
  DiffText = { bg = p.active_line },

  -- Spell
  SpellBad = { undercurl = true, sp = p.error_red },
  SpellCap = { undercurl = true, sp = p.warning },
  SpellRare = { undercurl = true, sp = p.keyword },
  SpellLocal = { undercurl = true, sp = p.info_color },

  -- gitsigns
  GitSignsAdd = { fg = p.diff_plus },
  GitSignsChange = { fg = p.diff_delta },
  GitSignsDelete = { fg = p.diff_minus },
  GitSignsTopdelete = { fg = p.diff_minus },
  GitSignsChangedelete = { fg = p.diff_delta },
  GitSignsUntracked = { fg = p.text_muted },

  -- snacks picker UI
  SnacksNormal = { link = "NormalFloat" },
  SnacksWinBorder = { link = "FloatBorder" },
  SnacksPickerBorder = { link = "FloatBorder" },
  SnacksPickerTitle = { fg = p.text_muted, bg = p.surface, bold = true },
  SnacksPickerDir = { fg = p.text_muted },
  SnacksPickerFile = { fg = p.fg },
  SnacksPickerMatch = { fg = p.accent, bold = true },
  SnacksPickerPrompt = { fg = p.accent },
  SnacksPickerCursorLine = { bg = p.active_line },
  SnacksPickerToggle = { fg = p.fg, bg = p.element_active },
}

for group, opts in pairs(groups) do
  hl(group, opts)
end
