-- Catppuccin Mocha, written as a standalone colorscheme. No plugin required.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end
vim.o.termguicolors = true
vim.o.background = "dark"
vim.g.colors_name = "mocha"

local p = {
  rosewater = "#f5e0dc",
  flamingo  = "#f2cdcd",
  pink      = "#f5c2e7",
  mauve     = "#cba6f7",
  red       = "#f38ba8",
  maroon    = "#eba0ac",
  peach     = "#fab387",
  yellow    = "#f9e2af",
  green     = "#a6e3a1",
  teal      = "#94e2d5",
  sky       = "#89dceb",
  sapphire  = "#74c7ec",
  blue      = "#89b4fa",
  lavender  = "#b4befe",
  text      = "#cdd6f4",
  subtext1  = "#bac2de",
  subtext0  = "#a6adc8",
  overlay2  = "#9399b2",
  overlay1  = "#7f849c",
  overlay0  = "#6c7086",
  surface2  = "#585b70",
  surface1  = "#45475a",
  surface0  = "#2b2c3d",
  base      = "#191927",
  mantle    = "#141421",
  crust     = "#0f0f19",
}

local diff = {
  add    = "#273a30",
  change = "#27384f",
  delete = "#3f2d3d",
  text   = "#3b4261",
}

local hl = function(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

local groups = {
  -- Editor UI
  Normal       = { fg = p.text, bg = p.base },
  NormalNC     = { fg = p.text, bg = p.base },
  NormalFloat  = { fg = p.text, bg = p.mantle },
  FloatBorder  = { fg = p.surface2, bg = p.mantle },
  FloatTitle   = { fg = p.mauve, bg = p.mantle, bold = true },
  Cursor       = { fg = p.base, bg = p.rosewater },
  lCursor      = { fg = p.base, bg = p.rosewater },
  TermCursor   = { fg = p.base, bg = p.rosewater },
  CursorLine   = { bg = p.surface0 },
  CursorColumn = { bg = p.surface0 },
  ColorColumn  = { bg = p.mantle },
  LineNr       = { fg = p.surface1 },
  CursorLineNr = { fg = p.lavender },
  SignColumn   = { fg = p.surface1, bg = p.base },
  FoldColumn   = { fg = p.surface1, bg = p.base },
  Folded       = { fg = p.overlay1, bg = p.surface0 },
  Visual       = { bg = p.surface1 },
  VisualNOS    = { bg = p.surface1 },
  MatchParen   = { fg = p.peach, bold = true },
  Search       = { fg = p.base, bg = p.yellow },
  IncSearch    = { fg = p.base, bg = p.peach },
  CurSearch    = { fg = p.base, bg = p.peach },
  Substitute   = { fg = p.base, bg = p.red },
  WinSeparator = { fg = p.surface0 },
  VertSplit    = { fg = p.surface0 },
  EndOfBuffer  = { fg = p.base },
  NonText      = { fg = p.surface1 },
  Whitespace   = { fg = p.surface1 },
  SpecialKey   = { fg = p.surface1 },
  Conceal      = { fg = p.overlay1 },
  Directory    = { fg = p.blue },
  Title        = { fg = p.mauve, bold = true },

  -- Messages / cmdline
  ModeMsg    = { fg = p.text },
  MoreMsg    = { fg = p.green },
  Question   = { fg = p.green },
  ErrorMsg   = { fg = p.red, bold = true },
  WarningMsg = { fg = p.yellow },
  MsgArea    = { fg = p.text },

  -- Statusline / tabline
  StatusLine   = { fg = p.text, bg = p.mantle },
  StatusLineNC = { fg = p.overlay1, bg = p.mantle },
  TabLine      = { fg = p.overlay1, bg = p.base },
  TabLineSel   = { fg = p.text, bg = p.surface0 },
  TabLineFill  = { bg = p.base },
  WinBar       = { fg = p.text, bg = p.base },
  WinBarNC     = { fg = p.overlay1, bg = p.base },

  -- Popup menu
  Pmenu        = { fg = p.text, bg = p.mantle },
  PmenuSel     = { fg = p.base, bg = p.blue },
  PmenuSbar    = { bg = p.mantle },
  PmenuThumb   = { bg = p.surface2 },
  WildMenu     = { fg = p.base, bg = p.blue },
  QuickFixLine = { bg = p.surface0 },

  -- Base syntax
  Comment        = { fg = p.overlay0, italic = true },
  Constant       = { fg = p.peach },
  String         = { fg = p.green },
  Character      = { fg = p.green },
  Number         = { fg = p.peach },
  Boolean        = { fg = p.peach },
  Float          = { fg = p.peach },
  Identifier     = { fg = p.text },
  Function       = { fg = p.blue },
  Statement      = { fg = p.mauve },
  Conditional    = { fg = p.mauve },
  Repeat         = { fg = p.mauve },
  Label          = { fg = p.mauve },
  Operator       = { fg = p.sky },
  Keyword        = { fg = p.mauve },
  Exception      = { fg = p.mauve },
  PreProc        = { fg = p.pink },
  Include        = { fg = p.mauve },
  Define         = { fg = p.pink },
  Macro          = { fg = p.pink },
  PreCondit      = { fg = p.pink },
  Type           = { fg = p.yellow },
  StorageClass   = { fg = p.mauve },
  Structure      = { fg = p.yellow },
  Typedef        = { fg = p.yellow },
  Special        = { fg = p.pink },
  SpecialChar    = { fg = p.peach },
  Tag            = { fg = p.blue },
  Delimiter      = { fg = p.overlay2 },
  SpecialComment = { fg = p.overlay0, italic = true },
  Debug          = { fg = p.peach },
  Underlined     = { fg = p.blue, underline = true },
  Ignore         = { fg = p.overlay0 },
  Error          = { fg = p.red },
  Todo           = { fg = p.mauve, bold = true },

  -- Treesitter captures
  ["@comment"]               = { fg = p.overlay0, italic = true },
  ["@comment.documentation"] = { fg = p.overlay0, italic = true },
  ["@variable"]              = { fg = p.text },
  ["@variable.builtin"]      = { fg = p.red },
  ["@variable.parameter"]    = { fg = p.maroon },
  ["@variable.member"]       = { fg = p.teal },
  ["@property"]              = { fg = p.teal },
  ["@field"]                 = { fg = p.teal },

  ["@constant"]         = { fg = p.peach },
  ["@constant.builtin"] = { fg = p.peach },
  ["@constant.macro"]   = { fg = p.peach },
  ["@number"]           = { fg = p.peach },
  ["@number.float"]     = { fg = p.peach },
  ["@boolean"]          = { fg = p.peach },

  ["@string"]                = { fg = p.green },
  ["@string.regexp"]         = { fg = p.peach },
  ["@string.escape"]         = { fg = p.pink },
  ["@string.special"]        = { fg = p.pink },
  ["@string.special.symbol"] = { fg = p.pink },
  ["@string.special.url"]    = { fg = p.rosewater, underline = true },
  ["@character"]             = { fg = p.green },
  ["@character.special"]     = { fg = p.pink },

  ["@function"]             = { fg = p.blue },
  ["@function.call"]        = { fg = p.blue },
  ["@function.builtin"]     = { fg = p.red },
  ["@function.macro"]       = { fg = p.pink },
  ["@function.method"]      = { fg = p.blue },
  ["@function.method.call"] = { fg = p.blue },
  ["@constructor"]          = { fg = p.sapphire },
  ["@attribute"]            = { fg = p.yellow },

  ["@type"]            = { fg = p.yellow },
  ["@type.builtin"]    = { fg = p.yellow },
  ["@type.definition"] = { fg = p.yellow },
  ["@type.qualifier"]  = { fg = p.mauve },

  ["@keyword"]             = { fg = p.mauve },
  ["@keyword.function"]    = { fg = p.mauve },
  ["@keyword.operator"]    = { fg = p.mauve },
  ["@keyword.import"]      = { fg = p.mauve },
  ["@keyword.storage"]     = { fg = p.mauve },
  ["@keyword.repeat"]      = { fg = p.mauve },
  ["@keyword.return"]      = { fg = p.mauve },
  ["@keyword.conditional"] = { fg = p.mauve },
  ["@keyword.exception"]   = { fg = p.mauve },
  ["@keyword.directive"]   = { fg = p.pink },
  ["@keyword.coroutine"]   = { fg = p.mauve },

  ["@operator"]              = { fg = p.sky },
  ["@punctuation.delimiter"] = { fg = p.overlay2 },
  ["@punctuation.bracket"]   = { fg = p.overlay2 },
  ["@punctuation.special"]   = { fg = p.pink },

  ["@module"]    = { fg = p.lavender },
  ["@namespace"] = { fg = p.lavender },
  ["@label"]     = { fg = p.sapphire },

  ["@tag"]           = { fg = p.mauve },
  ["@tag.attribute"] = { fg = p.blue },
  ["@tag.delimiter"] = { fg = p.sky },

  -- Markup
  ["@markup.heading"]       = { fg = p.mauve, bold = true },
  ["@markup.strong"]        = { fg = p.maroon, bold = true },
  ["@markup.italic"]        = { fg = p.maroon, italic = true },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.raw"]           = { fg = p.green },
  ["@markup.raw.block"]     = { fg = p.green },
  ["@markup.link"]          = { fg = p.blue },
  ["@markup.link.label"]    = { fg = p.sapphire },
  ["@markup.link.url"]      = { fg = p.rosewater, underline = true },
  ["@markup.list"]          = { fg = p.peach },
  ["@markup.quote"]         = { fg = p.overlay1, italic = true },
  ["@markup.math"]          = { fg = p.blue },

  ["@diff.plus"]  = { fg = p.green },
  ["@diff.minus"] = { fg = p.red },
  ["@diff.delta"] = { fg = p.yellow },

  -- LSP semantic tokens
  ["@lsp.type.namespace"]     = { link = "@module" },
  ["@lsp.type.type"]          = { link = "@type" },
  ["@lsp.type.class"]         = { link = "@type" },
  ["@lsp.type.enum"]          = { link = "@type" },
  ["@lsp.type.interface"]     = { link = "@type" },
  ["@lsp.type.struct"]        = { link = "@type" },
  ["@lsp.type.typeParameter"] = { link = "@type" },
  ["@lsp.type.parameter"]     = { link = "@variable.parameter" },
  ["@lsp.type.variable"]      = { link = "@variable" },
  ["@lsp.type.property"]      = { link = "@property" },
  ["@lsp.type.enumMember"]    = { link = "@constant" },
  ["@lsp.type.function"]      = { link = "@function" },
  ["@lsp.type.method"]        = { link = "@function.method" },
  ["@lsp.type.macro"]         = { link = "@function.macro" },
  ["@lsp.type.keyword"]       = { link = "@keyword" },
  ["@lsp.type.comment"]       = { link = "@comment" },
  ["@lsp.type.string"]        = { link = "@string" },
  ["@lsp.type.number"]        = { link = "@number" },
  ["@lsp.type.operator"]      = { link = "@operator" },
  ["@lsp.type.decorator"]     = { link = "@attribute" },

  -- Diagnostics
  DiagnosticError = { fg = p.red },
  DiagnosticWarn  = { fg = p.yellow },
  DiagnosticInfo  = { fg = p.sky },
  DiagnosticHint  = { fg = p.teal },
  DiagnosticOk    = { fg = p.green },
  DiagnosticVirtualTextError = { fg = p.red },
  DiagnosticVirtualTextWarn  = { fg = p.yellow },
  DiagnosticVirtualTextInfo  = { fg = p.sky },
  DiagnosticVirtualTextHint  = { fg = p.teal },
  DiagnosticUnderlineError = { undercurl = true, sp = p.red },
  DiagnosticUnderlineWarn  = { undercurl = true, sp = p.yellow },
  DiagnosticUnderlineInfo  = { undercurl = true, sp = p.sky },
  DiagnosticUnderlineHint  = { undercurl = true, sp = p.teal },
  DiagnosticUnnecessary = { fg = p.overlay0 },
  DiagnosticDeprecated  = { strikethrough = true },

  LspInlayHint = { fg = p.overlay1, bg = p.surface0 },
  LspReferenceText  = { bg = p.surface1 },
  LspReferenceRead  = { bg = p.surface1 },
  LspReferenceWrite = { bg = p.surface1 },

  -- vimdiff
  DiffAdd    = { bg = diff.add },
  DiffChange = { bg = diff.change },
  DiffDelete = { fg = p.red, bg = diff.delete },
  DiffText   = { bg = diff.text },

  -- Spell
  SpellBad   = { undercurl = true, sp = p.red },
  SpellCap   = { undercurl = true, sp = p.yellow },
  SpellRare  = { undercurl = true, sp = p.mauve },
  SpellLocal = { undercurl = true, sp = p.sky },

  -- gitsigns
  GitSignsAdd          = { fg = p.green },
  GitSignsChange       = { fg = p.yellow },
  GitSignsDelete       = { fg = p.red },
  GitSignsTopdelete    = { fg = p.red },
  GitSignsChangedelete = { fg = p.yellow },
  GitSignsUntracked    = { fg = p.overlay1 },

  -- snacks picker UI
  SnacksNormal       = { link = "NormalFloat" },
  SnacksWinBorder    = { link = "FloatBorder" },
  SnacksPickerBorder = { link = "FloatBorder" },
  SnacksPickerTitle  = { fg = p.mauve, bg = p.mantle },
  SnacksPickerDir    = { fg = p.overlay1 },
  SnacksPickerFile   = { fg = p.text },
  SnacksPickerMatch  = { fg = p.mauve, bold = true },
  SnacksPickerPrompt = { fg = p.mauve },
  SnacksPickerCursorLine = { link = "CursorLine" },
  SnacksPickerToggle = { fg = p.base, bg = p.blue },
}

for group, opts in pairs(groups) do
  hl(group, opts)
end
